# Jeff Johnston
# 12 Mar 2021
#
# docker-compose file for portainer (portainer.io)
# Configured with:
#   Uses wildcard certificate from Traefik proxy (../traefik/)
#   Secure portainer service (portainer.example.com)

version: '3.6'

services:
  portainer:
    container_name: 'portainer'
    image: 'portainer/portainer-ce'
    security_opt:
      - no-new-privileges:true
    networks:
      - 'traefik'
    volumes:
      - 'portainer_data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels:
      - 'traefik.http.routers.portainer.rule=Host(`portainer.example.com`)'
      - 'traefik.http.routers.portainer.tls=true'
      - 'traefik.http.routers.portainer.entrypoints=websecure'
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

volumes:
   portainer_data:
     driver: local

networks:
  traefik:
    external: true
